# Generated by Django 4.1.4 on 2022-12-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_department_college_alter_principal_college_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fuletype',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fuletype', models.ManyToManyField(to='app1.fuletype')),
            ],
            options={
                'db_table': 'carmodel',
            },
        ),
    ]
